modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "kubejs_curios"
version = "${version}"
displayName = "KubeJS Curios"
authors = "Prunoideae"
description = '''
Adds Curios support for KubeJS
'''
logoFile = "icon.png"

[[dependencies.kubejs_curios]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs_curios]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejs_curios]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs_curios]]
modId = "curios"
mandatory = true
versionRange = "[1.18-5.0.2.4,)"

[[dependencies.kubejs_curios]]
modId = "kubejs"
mandatory = true
versionRange = "[1802.5.1-build.353,)"
